-- MySQL Script generated by MySQL Workbench
-- Mon Dec 12 15:33:20 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema recurDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema recurDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `recurDB` DEFAULT CHARACTER SET utf8 ;
USE `recurDB` ;

-- -----------------------------------------------------
-- Table `recurDB`.`UserType`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `recurDB`.`UserType`
(
	`userTypeID` INT NOT NULL AUTO_INCREMENT
	,`userType` VARCHAR(45) NOT NULL
	,CONSTRAINT `PK_UserType` PRIMARY KEY (`userTypeID`)
	,UNIQUE INDEX `ix_uq_userTypeID` (`userTypeID` ASC)
    ,UNIQUE INDEX `ix_uq_userType` (`userType` ASC)
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `recurDB`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `recurDB`.`User`
(
	`userID` INT NOT NULL AUTO_INCREMENT
	,`userTypeID_FK` INT NOT NULL
	,`username` VARCHAR(25) NOT NULL
	,`password` VARCHAR(20) NOT NULL COMMENT 'Encrypt using SHA256'
	,`firstName` VARCHAR(30) NULL
	,`lastName` VARCHAR(30) NULL
	,`email` VARCHAR(80) NULL
	,`phone` VARCHAR(15) NULL
	,CONSTRAINT `PK_User` PRIMARY KEY (`userID`)
	,UNIQUE INDEX `ix_uq_username` (`username` ASC)
	,UNIQUE INDEX `ix_uq_userID` (`userID` ASC)
	,INDEX `ix_fk_user_userType` (`userTypeID_FK` ASC)
	,CONSTRAINT `FK_User_UserType` FOREIGN KEY (`userTypeID_FK`)
		REFERENCES `recurDB`.`UserType` (`userTypeID`)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `recurDB`.`Event`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `recurDB`.`Event`
(
	`eventID` INT NOT NULL AUTO_INCREMENT
	,`scheduleID_FK` INT NOT NULL
	,`name` VARCHAR(50) NOT NULL
	,`description` VARCHAR(200) NOT NULL
	,CONSTRAINT `PK_Event` PRIMARY KEY (`eventID`)
	,UNIQUE INDEX `ix_uq_eventID` (`eventID` ASC)
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `recurDB`.`Schedule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `recurDB`.`Schedule`
(
	`scheduleID` INT NOT NULL AUTO_INCREMENT
	,`userID_FK` INT NOT NULL
	,`eventID_FK` INT NOT NULL
	,`repeatAfterDays` INT NOT NULL
	,`repeatTime` VARCHAR(10) NOT NULL
	,CONSTRAINT `PK_Schedule` PRIMARY KEY (`scheduleID`)
	,UNIQUE INDEX `ix_uq_scheduleID` (`scheduleID` ASC)
	,INDEX `ix_fk_schedule_user` (`userID_FK` ASC)
	,INDEX `ix_fk_schedule_event` (`eventID_FK` ASC)
	,CONSTRAINT `FK_Schedule_User` FOREIGN KEY (`userID_FK`)
		REFERENCES `recurDB`.`User` (`userID`)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
	,CONSTRAINT `FK_Schedule_Event` FOREIGN KEY (`eventID_FK`)
		REFERENCES `recurDB`.`Event` (`eventID`)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
